version: '3.8'

services:
  bosch-search:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models:ro  # Read-only mount of local models
      - ./chroma_db:/app/chroma_db  # ChromaDB data directory
      - ./uploads:/app/uploads
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 